FROM golang:1.13.0-alpine3.10
LABEL maintainer="Jaskaranbir Dhillon"

ENV CGO_ENABLED=0 \
    GOOS=linux

RUN apk add --update git

WORKDIR $GOPATH/src/github.com/Jaskaranbir/dapp-fs

COPY ./ ./

CMD go test -v ./...
